<?php

namespace NP\Bundle\ResourcesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcesRepository extends EntityRepository {

    public function deleteOne($id)
    {
        $this->deleteGroup(array($id));
    }

    public function deleteGroup($ids)
    {
        $qb = $this->createQueryBuilder('n');

        $qb->delete('NPResourcesBundle:Resources', 'n')
                ->where($qb->expr()->in('n.id', $ids))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }
}
