<?php

namespace NP\Bundle\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository {

    public function deleteOne($id)
    {
        $this->deleteGroup(array($id));
    }

    public function deleteGroup($ids)
    {
        $qb = $this->createQueryBuilder('n');

        $qb->delete('NPNewsBundle:News', 'n')
                ->where($qb->expr()->in('n.id', $ids))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }

    public function publishGroup($id) {
        $qb = $this->createQueryBuilder('n');

        $qb->update('NPNewsBundle:News', 'n')
                ->set('n.published', 1)
                ->where($qb->expr()->in('n.id', $id))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }

    public function unpublishGroup($id) {
        $qb = $this->createQueryBuilder('n');
        $qb->update('NPNewsBundle:News', 'n')
                ->set('n.published', 0)
                ->where($qb->expr()->in('n.id', $id))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }
}
