np_guest_book_fronttestimonial_list_json:
    pattern:  /testimonial.{format}
    defaults: { _controller: NPGuestBookBundle:FrontTestimonial:list, _format: json }
np_guest_book_fronttestimonial_new:
    pattern:  /testimonial_new
    defaults: { _controller: NPGuestBookBundle:FrontTestimonial:new }
